#
#	Globaler Makefile fuer alle Projekt in der CodeBox IDE
#

PROJECTS=AnalogIn DigitalOut LichtSensor PIRSensor Polling PwmOut PwmOutPeriod RGBLEDStrip RGBLEDStripSPI Schrittmotor SDCardFS SDCardIO Ethernet

all: 
	for dir in $(PROJECTS); do \
    	$(MAKE) -C $$dir all; \
	done
	echo "*.bin Dateien aus Verzeichnis/MCU_K64F mittels rechter Maustaste auf Board downloaden"
	
clean: 
	for dir in $(PROJECTS); do \
    	$(MAKE) -C $$dir clean; \
	done