#!/bin/bash
#
#   SQL Daten ausgeben
 
# HTTP Header fuer Client
echo "Content-type: text/plain"
echo ""
 
export SQL="SELECT * FROM data;"

echo "$SQL"
echo ""
mysql -uwww-data -pmbed sensoren <<EOF
	${SQL}
EOF
